version: '3.8'

services:
  # Container 1: O Microsserviço C#
  meu-backend:
    container_name: microsservico-net
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80" # Mapeia a porta 5000 da sua máquina física para a porta 80 interna do container
    depends_on:
      - fila-rabbitmq # Garante que o microsserviço espere o RabbitMQ subir primeiro

  # Container 2: RabbitMQ com Painel de Gerenciamento Visual
  fila-rabbitmq:
    image: rabbitmq:3-management
    container_name: fila-rabbitmq
    ports:
      - "5672:5672"   # Porta de comunicação interna de dados (AMQP)
      - "15672:15672" # Porta do painel de controle web (Dashboard)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
